  language: java
  
 
  addons:
    sonarcloud:
      organization: "ngendron-github"
      token:
        secure: "n18fcab8a41314c509e65f1f14a442bf137e29cf0"

  jdk:
  - oraclejdk8      
        
  script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

  cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'