  language: java
  
 
  addons:
    sonarcloud:
      organization: "ngendron-github"
      token:
        secure: "565538301b2ebbfe2072170276c9aba6666b9156"

  jdk:
  - oraclejdk8      
        
  script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

  cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'