CREATE TABLE IF NOT EXISTS QUESTION_NPG(
	id INTEGER PRIMARY KEY,
	question TEXT NOT NULL,
	reponse TEXT NOT NULL,
	difficulte INTEGER NOT NULL,
	reference TEXT NOT NULL UNIQUE,
	source TEXT);

CREATE TABLE IF NOT EXISTS QUESTION_NPG_JOUEE(
	question_id INTEGER NOT NULL,
	date_lecture DATETIME NOT NULL,
	lecteur TEXT);

CREATE TABLE IF NOT EXISTS QUESTION_QALS(
	id INTEGER PRIMARY KEY,
	question TEXT NOT NULL,
	reponse TEXT NOT NULL,
	theme_id INTEGER NOT NULL);
	
CREATE TABLE IF NOT EXISTS THEME_QALS(
	id INTEGER PRIMARY KEY,
	categorie INTEGER NOT NULL,
	theme TEXT NOT NULL,
	reference TEXT NOT NULL UNIQUE,
	source TEXT);

CREATE TABLE IF NOT EXISTS THEME_QALS_JOUEE(
	theme_id INTEGER NOT NULL,
	date_lecture DATETIME NOT NULL,
	lecteur TEXT);

CREATE TABLE IF NOT EXISTS QUESTION_JD(
	id INTEGER PRIMARY KEY,
	theme TEXT NOT NULL,
	question TEXT NOT NULL,
	reponse TEXT NOT NULL,
	reference TEXT NOT NULL UNIQUE,
	source TEXT);

CREATE TABLE IF NOT EXISTS QUESTION_JD_JOUEE(
	question_id INTEGER NOT NULL,
	date_lecture DATETIME NOT NULL,
	lecteur TEXT);

CREATE TABLE IF NOT EXISTS QUESTION_FAF(
	id INTEGER PRIMARY KEY,
	categorie INTEGER NOT NULL,
	theme TEXT NOT NULL,
	question TEXT NOT NULL,
	reponse TEXT NOT NULL,
	reference TEXT NOT NULL UNIQUE,
	source TEXT);

CREATE TABLE IF NOT EXISTS QUESTION_FAF_JOUEE(
	question_id INTEGER NOT NULL,
	date_lecture DATETIME NOT NULL,
	lecteur TEXT);

CREATE TABLE IF NOT EXISTS SYNCHRO(
	id INTEGER PRIMARY KEY,
	cle TEXT NOT NULL,
	valeur INTEGER NOT NULL,
	date_derniere_synchro DATETIME NOT NULL);
